fix(mongodb): regression 'unexpected "js-yaml.js" output while parsing config'
The change introduced in 1a77f8fb will lead to a regression during mongo
startup when *not* using `customConf`.

The file was previously empty and mongod happily used it.
The previous fix introduces a line break in the file - even when not
using `customConf` - which will result in this error message during init:

```plain
<... truncated ...>
***** EXTRA-INIT: Waiting until mongod is fully up and running
error: unexpected "js-yaml.js" output while parsing config:
***** EXTRA-INIT: Waiting for mongod...
<... truncated ...>
***** EXTRA-INIT: mongod is not running.. Stopping hard
```

This commit fixes that issue by ensuring no additional line breaks
are written to `custom.conf`.

Sorry for any inconvenience caused.

Related PR: https://github.com/groundhog2k/helm-charts/pull/1519
Commit introducing the regression: 1a77f8fb69079242d6744fdff9d75024c945f6b5

Signed-off-by: Christoph Hoopmann <choopm@0pointer.org>